# Generated by Django 4.1.7 on 2023-05-23 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_comment_listing_listing_price_alter_bid_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='category',
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.ManyToManyField(related_name='category_listings', to='auctions.category'),
        ),
    ]
