# Generated by Django 4.1.7 on 2023-05-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_category_listings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='listings',
            field=models.ManyToManyField(blank=True, related_name='category_listings', to='auctions.listing'),
        ),
    ]
