# Generated by Django 4.1.7 on 2023-05-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_category_listings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.URLField(default='auctions\\images\\default-img.png'),
        ),
    ]
