# Generated by Django 4.1.7 on 2023-07-22 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_remove_listing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='open_for_bid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listing_owners', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
