# Generated by Django 4.1.7 on 2023-07-22 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_listing_open_for_bid_listing_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bidding_winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_winners', to=settings.AUTH_USER_MODEL),
        ),
    ]
