# Generated by Django 4.1.7 on 2023-07-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_remove_listing_start_price_bid_start_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='start_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
    ]
