# Generated by Django 4.1.7 on 2023-07-27 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_listing_start_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='start_price',
        ),
    ]
