# Generated by Django 4.1.7 on 2023-07-27 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_remove_bid_start_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='listings',
        ),
    ]
